%YAML 1.2
---
root: true
env:
  commonjs: true
  es2022: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
plugins:
  - custom
rules:
  custom/name-length:
    - error
    - 50
...
